---
kind: Template
apiVersion: v1
metadata:
  name: secret-docker-cfg-stringdata
  annotations:
    openshift.io/display-name: .docker/config.json secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}"
  type: kubernetes.io/dockerconfigjson
  stringData: 
    .dockerconfigjson: >-
      {
        "auths": {
          "${REPO_FQDN}": {
            "username": "${REPO_USERNAME}",
            "password": "${REPO_PASSWORD}",
            "auth": "${REPO_AUTH}"
          }
        }
      }
parameters:
- name: NAME
  displayName: Name
  description: The name of secret.
  required: true
- name: REPO_FQDN
  displayName: Repository FQDN
  description: FQDN for the image repository
  required: true
- name: REPO_USERNAME
  displayName: Repository Username
  description: "The plan text repository username. Can use this and REPO_PASSWORD, or REPO_AUTH parameter."
- name: REPO_PASSWORD
  displayName: Repository Password
  description: "The plan text repository password. Can use this and REPO_USERNAME, or REPO_AUTH parameter."
- name: REPO_AUTH
  displayName: Repository auth
  description: "The username:password base64 encoded. Ex 'echo -n USER:PASS | base64 -w0'. Can use this or REPO_USERNAME and REPO_PASSWORD fields."
